# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/perf/sensor_ts_header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"common/perf/sensor_ts_header.proto\x12\x0fnio.ad.messages\"\xd5\x04\n\x0eSensorTSHeader\x12\x1b\n\x13sensor_camera_fw_ts\x18\x01 \x03(\x04\x12\x1b\n\x13sensor_camera_fn_ts\x18\x02 \x03(\x04\x12\x1b\n\x13sensor_camera_rn_ts\x18\x03 \x03(\x04\x12\x1b\n\x13sensor_camera_fl_ts\x18\x04 \x03(\x04\x12\x1b\n\x13sensor_camera_fr_ts\x18\x05 \x03(\x04\x12\x1b\n\x13sensor_camera_rr_ts\x18\x06 \x03(\x04\x12\x1b\n\x13sensor_camera_rl_ts\x18\x07 \x03(\x04\x12\x1c\n\x14sensor_camera_sfw_ts\x18\x08 \x03(\x04\x12\x1d\n\x15sensor_camera_srcw_ts\x18\t \x03(\x04\x12\x1c\n\x14sensor_camera_slw_ts\x18\n \x03(\x04\x12\x1c\n\x14sensor_camera_srw_ts\x18\x0b \x03(\x04\x12\x17\n\x0fsensor_lidar_ts\x18\x0c \x03(\x04\x12\x1d\n\x15sensor_radar_front_ts\x18\r \x03(\x04\x12\x1a\n\x12sensor_radar_fl_ts\x18\x0e \x03(\x04\x12\x1a\n\x12sensor_radar_fr_ts\x18\x0f \x03(\x04\x12\x1a\n\x12sensor_radar_rl_ts\x18\x10 \x03(\x04\x12\x1a\n\x12sensor_radar_rr_ts\x18\x11 \x03(\x04\x12\x0e\n\x06imu_ts\x18\x12 \x03(\x04\x12\x0f\n\x07gnss_ts\x18\x13 \x03(\x04\x12\x1a\n\x12vehicle_in_10ms_ts\x18\x14 \x03(\x04\x12\x1a\n\x12vehicle_in_50ms_ts\x18\x15 \x03(\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.perf.sensor_ts_header_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORTSHEADER._serialized_start=56
  _SENSORTSHEADER._serialized_end=653
# @@protoc_insertion_point(module_scope)
